2024-01-04 23:10:41,574 INFO    MainThread:23521 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-04 23:10:41,574 INFO    MainThread:23521 [wandb_setup.py:_flush():76] Configure stats pid to 23521
2024-01-04 23:10:41,574 INFO    MainThread:23521 [wandb_setup.py:_flush():76] Loading settings from /home/anto/.config/wandb/settings
2024-01-04 23:10:41,574 INFO    MainThread:23521 [wandb_setup.py:_flush():76] Loading settings from /home/anto/University/Driving-Visual-Attention/wandb/settings
2024-01-04 23:10:41,574 INFO    MainThread:23521 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-04 23:10:41,574 INFO    MainThread:23521 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-04 23:10:41,574 INFO    MainThread:23521 [wandb_init.py:_log_setup():524] Logging user logs to /home/anto/University/Driving-Visual-Attention/wandb/run-20240104_231041-4o5tkv8e/logs/debug.log
2024-01-04 23:10:41,574 INFO    MainThread:23521 [wandb_init.py:_log_setup():525] Logging internal logs to /home/anto/University/Driving-Visual-Attention/wandb/run-20240104_231041-4o5tkv8e/logs/debug-internal.log
2024-01-04 23:10:41,574 INFO    MainThread:23521 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fe1d449f910>
2024-01-04 23:10:41,575 INFO    MainThread:23521 [wandb_init.py:init():564] calling init triggers
2024-01-04 23:10:41,575 INFO    MainThread:23521 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-01-04 23:10:41,575 INFO    MainThread:23521 [wandb_init.py:init():614] starting backend
2024-01-04 23:10:41,575 INFO    MainThread:23521 [wandb_init.py:init():618] setting up manager
2024-01-04 23:10:41,577 INFO    MainThread:23521 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-01-04 23:10:41,578 INFO    MainThread:23521 [wandb_init.py:init():624] backend started and connected
2024-01-04 23:10:41,583 INFO    MainThread:23521 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-01-04 23:10:41,583 INFO    MainThread:23521 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-04 23:10:41,584 INFO    MainThread:23521 [wandb_init.py:init():716] updated telemetry
2024-01-04 23:10:41,662 WARNING MainThread:23521 [wandb_init.py:init():1192] interrupted
Traceback (most recent call last):
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 732, in init
    run._populate_git_info()
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 842, in _populate_git_info
    self._remote_url, self._commit = repo.remote_url, repo.last_commit
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/site-packages/wandb/sdk/lib/gitlib.py", line 119, in last_commit
    if not self.repo.head or not self.repo.head.is_valid():
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/site-packages/git/refs/symbolic.py", line 442, in is_valid
    self.object
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/site-packages/git/refs/symbolic.py", line 267, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/site-packages/git/objects/base.py", line 94, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/site-packages/git/db.py", line 40, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/site-packages/git/cmd.py", line 1383, in get_object_header
    cmd = self._get_persistent_cmd("cat_file_header", "cat_file", batch_check=True)
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/site-packages/git/cmd.py", line 1362, in _get_persistent_cmd
    cmd = self._call_process(cmd_name, *args, **options)
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/site-packages/git/cmd.py", line 1316, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/site-packages/git/cmd.py", line 988, in execute
    proc = Popen(
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/anto/Apps/Anaconda3/envs/dlib/lib/python3.8/subprocess.py", line 1676, in _execute_child
    part = os.read(errpipe_read, 50000)
KeyboardInterrupt
